### ISSUE TITLE
mapReduce does not work anymore

### ISSUE THREAD

**Issue by zvictor** [jhoxray/meteor-mongo-extensions#4]
not `out: inline` mapReduce calls do not work anymore on meteor 0.6.5 and newer (or any meteor using mongodb > 1.3.7) because "a long standing but unnoticed bug was recently exposed by recent commit" [mongodb/node-mongodb-native#1016].

It seems to me that meteor is setting `readPreference` somewhere, which does not allow us to use mapReduce properly.

As example, using **merge** as **out** key the following error has been thrown

``` js
    out: {
      merge: "connexions_tmp"
    }
```

``` haskell
Exception in callback of Meteor.http.call Error: a readPreference can only be provided when performing an inline mapReduce 
at Collection.mapReduce (/tmp/slirp/.demeteorized/node_modules/mongodb/lib/mongodb/collection.js:1170:13) 
at app/server/aggregation.js:39:19 
at Db.collection (/tmp/slirp/.demeteorized/node_modules/mongodb/lib/mongodb/db.js:476:44) 
at _callMapReduce (app/server/aggregation.js:35:26) 
```

**Comment by arunoda** [comment]
By default meteor starts with safe: true. which is equalant to w: majority I think. But you can override it via the mongoUrl options.

**Comment by jhoxray** [comment]
@zvictor thanks for pointing it out. I think we should put some pressure on Meteor devs to pay attention to aggregation framework support, it's quite important for any semi-serious data-related application.

**Comment by zvictor** [comment]
@jhoxray It would be amazing to have them looking more incisively to the aggregation support but for now it really does not seem to be their priority. Mongo enhancements are expected to happen only ["after after" the launch of Meteor 1.0](https://trello.com/c/C91INHmj/27-minimongo-enhancements) and I don't guess they will add aggregation support before that.

I am afraid we are alone for now.

**Comment by zvictor** [comment]
@arunoda Thank you for pointing that. I do not completely understand the implications of the safe/unsafe modes so I will research and see if it fits for me.

**Comment by jhoxray** [comment]
@zvictor mapReduce is fixed!

**Comment by zvictor** [comment]
@jhoxray Thank you! It is really amazing to see progress on this matter!
However I could not confirm the solution because I faced the issue #5

**Comment by zvictor** [comment]
@jhoxray It seemed to work initially, but probably because I updated the Meteor and dependencies it can not work anymore. Can you please run it again and see if it is working to you? I am using mongodb-aggregation v0.1.71 and meteor v0.6.5.1

``` haskell
Exception in callback of async function Error: a readPreference can only be provided when performing an inline mapReduce
    at Collection.mapReduce (/mnt/data/2/node_modules/mongodb/lib/mongodb/collection.js:1170:13)
    at Meteor.methods._callMapReduce (packages/mongodb-aggregation.js:49:13)
    at maybeAuditArgumentChecks (packages/livedata.js:2041:12)
    at packages/livedata.js:1970:18
    at _.extend.withValue (packages/meteor.js:837:17)
    at _.extend.apply (packages/livedata.js:1969:45)
    at _.extend.mapReduce (packages/mongodb-aggregation.js:85:21)
```

**Comment by zvictor** [comment]
Now I am suspecting that the error is only happening on mongodb previous to version 2.4.
I hope I can confirm this info soon.

**Comment by jhoxray** [comment]
Thanks Victor, please do and if the issue persists with later versions as well I'll look into it.

**Comment by zvictor** [comment]
I tested it on mongodb 2.4.4, 2.4.5, 2.4.6 and 2.2(modulus.io instance).
It works ONLY on 2.4.4.

**Comment by zvictor** [comment]
I think I found a reasonable solution.
We have to force our client to use the primary mongo, and I realized that we have a very simple way to do that, that is overriding it on `options`.

``` coffee
  mapReduce: (map, reduce, options)->
    options = options || {};
    options.readPreference = "primary";
    _callMapReduce @_name, map, reduce, options
```

You can see that in action in my fork: [server.coffee](https://github.com/zvictor/meteor-mongo-server/blob/master/server.coffee)
